import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";
import "./globals.css";

const kumbh = Kumbh_Sans({
  variable: "--font-kumbh-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "DevJobs : Frontend Mentor Challenge",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${kumbh.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col
           bg-[#F4F6F8] dark:bg-[#121721]
          ">{children}</body>
    </html>
  );
}
